# The name of the application (no spaces)
app_name: Reservoir

# A brief description of the app.
description : Identifying geologic units from the macrostrat database that act as aquifers. 

# Your first and last name
user: Erika Ito

# Your email
email: erika.ito@outlook.com

# The primary language the application is written in - will be used for installing dependencies
# Current options are Python, R, and Go
language: R 3.3.1

# The NLP product to run the application against (NLP, NLP352, OCR, Cuneiform -- see input/README for more info)
product: NLP352, docid_terms

# How often the application should be run
frequency: once

# You can choose to specify a list of dictionaries, a list of terms, or both.
# If both dictionaries and terms are provided, all terms in the dictionary PLUS
# all listed terms will be used
dictionaries: Macrostrat units

# A list of terms used to subset the corpus
the word "aquifer"

# should the list of terms be case-sensitive?
case-sensitive: true
